### ISSUE TITLE
fix: Copiers scanning to the FTPS server give a `TLS_RESUME_FAILURE` error

### ISSUE THREAD

**Issue by bmiller08** [RenovoSolutions/cdk-aws-transfer-server#7]
**Describe the bug**
Scans to FTPS fails with a `TLS_RESUME_ERROR` in the logs and a `Communication with selected server is lost while sending image` on the copier

**To Reproduce**
1. Scan to FTPS server from a copier
2. Go to the [the cloudwatch log group](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Ftransfer$252Fs-29894d55c5754e619)
3. Find the correct username `irvinecopier`

**Expected behavior**
No errors.

**Screenshots**
NA

**Logs**
```txt
irvinecopier.6ca92af7b42a686c CONNECTED SourceIP=10.81.0.157 User=irvinecopier HomeDir=LOGICAL Client=UNKNOWN Role=arn:aws:iam::779153410995:role/cdk-renovo-transfer-serve-transferUserRoleCEA57BDE-ZB0BA1ADPIHD Protocol=FTPS TlsCipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
irvinecopier.6ca92af7b42a686c TLS_RESUME_FAILURE ServerId=s-29894d55c5754e619 User=irvinecopier Protocol=FTPS
irvinecopier.6ca92af7b42a686c DISCONNECTED
```

**Additional context**
This is with new `PASV` settings and a fresh attempt at FTPS in a single AZ.

**Comment by bmiller08** [comment]
https://repost.aws/questions/QURR9WVIbjQ-uYYFu_gMCdhw/ftp-transfer-family-ftps-tls-resume-failed

**Comment by bmiller08** [comment]
@ataraxia937 the fix seems like it might be straight forward by adding an [additional setting in the CDK code](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_transfer.CfnServer.ProtocolDetailsProperty.html#tlssessionresumptionmode) for `ProtocolDetails`

**Comment by ataraxia937** [comment]
I applied this and asked Javy to test again.

**Comment by bmiller08** [comment]
@ataraxia937 if you can PR that change I will approve
